import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "../auth/auth-provider";
import DashboardWrapper from "../layout/dashboard-wrapper";

export const metadata: Metadata = {
  title: "تسک بهمن سبز",
  description: "Generated by create Faeze Gholami",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthProvider>
          <DashboardWrapper>{children}</DashboardWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
